package com.ibilet.controllers;

import com.ibilet.entities.FlightDTO;
import com.ibilet.entities.User;
import com.ibilet.entities.Flight;
import com.ibilet.services.FlightService;
import jakarta.servlet.http.HttpSession;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;


import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.ExecutionException;

@Controller
public class FlightController {

    @Autowired
    private FlightService flightService;

    @GetMapping("/add-flight")
    public String showAddFlightForm(Model model) {
        return "add-flight";
    }

    @GetMapping("/flights")
    public String showFlights(Model model) throws ExecutionException, InterruptedException {
        List<FlightDTO> flights = flightService.getAllFlights(); // Assuming you have a method in FlightService to retrieve all flights
        model.addAttribute("flights", flights);
        return "flights";
    }

    @PostMapping("/add-flight")
    public String addFlight(String planeType, int seatsEconomy, int seatsFirst, double economyPrice, double firstPrice, String departureCity, String arrivalCity, String departureHour, String arrivalHour, String departureDate, String arrivalDate, double discountPercentageDus, double discountPercentageIntors, String flightType, HttpSession session, Model model) throws ExecutionException, InterruptedException {
        User user = (User) session.getAttribute("loggedInUser");

        if (user == null || user.getRole() != User.Role.AIRLINE) {
            return "redirect:/"; // or an error page
        }

        if(planeType.isEmpty() || seatsEconomy <= 0 || seatsFirst <= 0 || economyPrice <= 0 || firstPrice <= 0 || departureCity.isEmpty() || arrivalCity.isEmpty() || departureHour.isEmpty() || arrivalHour.isEmpty() || departureDate.isEmpty() || arrivalDate.isEmpty() || discountPercentageDus <= 0 || discountPercentageIntors <= 0 || flightType.isEmpty()){
            return "redirect:/add-flight"; // not validated
        }

        Flight createdFlight = new Flight();
        String autoGeneratedCode = UUID.randomUUID().toString();

        createdFlight.setCode(autoGeneratedCode);
        createdFlight.setPlaneType(planeType);
        createdFlight.setSeatsEconomy(seatsEconomy);
        createdFlight.setSeatsFirst(seatsFirst);
        createdFlight.setEconomyPrice(economyPrice);
        createdFlight.setFirstPrice(firstPrice);
        createdFlight.setDepartureCity(departureCity);
        createdFlight.setArrivalCity(arrivalCity);
        createdFlight.setDepartureHour(departureHour);
        createdFlight.setArrivalHour(arrivalHour);
        createdFlight.setDepartureDate(departureDate);
        createdFlight.setArrivalDate(arrivalDate);
        createdFlight.setDiscountPercentageDus(discountPercentageDus);
        createdFlight.setDiscountPercentageIntors(discountPercentageIntors);
        createdFlight.setFlightType(Flight.FlightType.valueOf(flightType));
        createdFlight.setCompanyId(user.getId());

        flightService.createFlight(createdFlight); // Save the flight using the FlightService
        return "redirect:/";
    }
}
